version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci --cache .npm --prefer-offline
        build:
          commands:
            - REACT_APP_CAPTCHA=${REACT_APP_CAPTCHA}
            - REACT_APP_EMAIL_SERVICE=${REACT_APP_EMAIL_SERVICE}
            - REACT_APP_EMAIL_TEMPLATE=${REACT_APP_EMAIL_TEMPLATE}
            - REACT_APP_EMAIL_USER=${REACT_APP_EMAIL_USER}
            - npm run build
      artifacts:
        baseDirectory: build
        files:
          - "**/*"
      cache:
        paths:
          - .npm/**/*
    appRoot: client
